# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - insview

on:
  push:
    branches:
      - azure
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'
  WORKING_DIRECTORY: nodejs/release
  PACKAGE_NAME: insview
  ARCHIVE_NAME: release.zip

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: 'Checkout Github Action'
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'npm install, build, and test'
        run: |
          npm install
          npm run build

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r ${{ env.ARCHIVE_NAME }} .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ env.ARCHIVE_NAME }}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.PACKAGE_NAME }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'insview'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5FA84747910449E78149FAFE40CAA2FB }}
          package: ${{ env.ARCHIVE_NAME }}